/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m11_exemplo_11_check_combo_boxes;

/**
 *
 * @author Joao
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxMenus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        checkBoxSopa = new javax.swing.JCheckBox();
        checkBoxSalada = new javax.swing.JCheckBox();
        checkBoxCafe = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensagens = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha o menu que pretende:");

        comboBoxMenus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu 1: 12€", "Menu 2: 15€", "Menu 3: 17€", "Menu 4: 19€" }));
        comboBoxMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMenusActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha os extras:");

        checkBoxSopa.setText("Sopa: 2€");
        checkBoxSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSopaActionPerformed(evt);
            }
        });

        checkBoxSalada.setText("Salada: 3€");
        checkBoxSalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSaladaActionPerformed(evt);
            }
        });

        checkBoxCafe.setText("Café: 1€");
        checkBoxCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCafeActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        campoMensagens.setColumns(20);
        campoMensagens.setRows(5);
        campoMensagens.setText("(faça as suas escolhas)");
        jScrollPane1.setViewportView(campoMensagens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(checkBoxSopa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(checkBoxSalada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(checkBoxCafe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxSopa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxSalada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxCafe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMenusActionPerformed
        // TODO add your handling code here:
        atualizaOutput();
    }//GEN-LAST:event_comboBoxMenusActionPerformed

    private void checkBoxSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSopaActionPerformed
        // TODO add your handling code here:
        atualizaOutput();
    }//GEN-LAST:event_checkBoxSopaActionPerformed

    private void checkBoxSaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSaladaActionPerformed
        // TODO add your handling code here:
        atualizaOutput();
    }//GEN-LAST:event_checkBoxSaladaActionPerformed

    private void checkBoxCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCafeActionPerformed
        // TODO add your handling code here:
        atualizaOutput();
    }//GEN-LAST:event_checkBoxCafeActionPerformed

    //----------------------------------------------------------------------------
    // 
    private void atualizaOutput(){
        int i = comboBoxMenus.getSelectedIndex(); 
        String[] nomesMenus = {"Menu #1","Menu #2","Menu #3","Menu #4"};
        int[]    precos     = {12, 15, 17, 19};
        int      total      = 0;
        
        campoMensagens.setText(nomesMenus[i]+"  --  "+precos[i]+"€");
        total = total + precos[i];
        
        if(checkBoxSopa.isSelected()){
            campoMensagens.append("\n  +Sopa: 2€");
            total = total+2;
        }
        if(checkBoxSalada.isSelected()){
            campoMensagens.append("\n  +Salada: 3€");
            total = total+3;
        }
        if(checkBoxCafe.isSelected()){
            campoMensagens.append("\n  +Café: 1€");
            total = total+1;
        }
        
        campoMensagens.append("\n-----------------------"
                              + "\n> TOTAL: "+total+"€");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoMensagens;
    private javax.swing.JCheckBox checkBoxCafe;
    private javax.swing.JCheckBox checkBoxSalada;
    private javax.swing.JCheckBox checkBoxSopa;
    private javax.swing.JComboBox<String> comboBoxMenus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
